version: "3.3"
services:
  bridge-contracts:
    build: .
    command: "true"
    env_file: ./deploy/.env
    networks:
      - poa-network-gabriel
    volumes:
      - ./output/:/contracts/deploy/output/


networks:
  poa-network-gabriel:
    external:
      name: poa-network-gabriel